[package]
name = "filewatcher"
version = "0.2.2"
authors = ["kingxsp <jin_hb_zh@126.com>"]
license = "Apache-2.0"
description = "File Watcher Library"
repository = "https://github.com/kingxsp/filewatcher"

[dependencies]
